/**
 * build-pack.mjs — compile picks.mjs → the searchable manifest + the M7 pack module.
 *
 *   npm run build:dawnlike
 *
 * Reads `picks.mjs`, slices each chosen 16x16 tile from the (gitignored) DawnLike sheets,
 * validates tags against the controlled vocab in `src/pack.ts`, and writes:
 *   - src/packs/dawnlike.manifest.json   the searchable schema (lean metadata, no image bytes)
 *   - src/packs/dawnlike.ts              the generated `SpritePack` for Characters (data-URIs)
 *
 * Off-vocab tag/size or unknown archetype FAILS the build. Missing/thin archetype coverage and
 * blank tiles WARN (so you can author incrementally). Items/Objects/Portraits go into the
 * manifest as a tagged catalogue only — they are not wired to the resolver yet.
 */
import fs from 'node:fs';
import path from 'node:path';
import picks from './picks.mjs';
import {
  REPO,
  loadVocab,
  readSheet,
  gridOf,
  cropTile,
  isBlank,
  pngToDataURI,
  sheetBase,
} from './lib.mjs';

const vocab = loadVocab();
const errors = [];
const warns = [];
const sheetCache = new Map();
const getSheet = rel => {
  if (!sheetCache.has(rel)) sheetCache.set(rel, readSheet(rel));
  return sheetCache.get(rel);
};

const manifest = [];
const characterSprites = [];
const seenIds = new Set();
const archetypeTileCount = Object.create(null);

for (const block of picks) {
  const { sheet, category, archetype, kind } = block;
  if (category === 'character' && !vocab.archetypes.has(archetype)) {
    errors.push(`${sheet}: unknown archetype "${archetype}"`);
    continue;
  }
  let png;
  try {
    png = getSheet(sheet);
  } catch {
    errors.push(`${sheet}: sheet not found under the DawnLike root (is Sprites/ present?)`);
    continue;
  }
  const { cols, rows } = gridOf(png);

  for (const tile of block.tiles ?? []) {
    const { col, row, tags = [], size, name = '' } = tile;
    const where = `${sheet} [${col},${row}]`;
    if (col < 0 || col >= cols || row < 0 || row >= rows) {
      errors.push(`${where}: out of range (sheet is ${cols}x${rows})`);
      continue;
    }
    // Validate vocab for characters (the matched category). Other categories use free tags.
    if (category === 'character') {
      for (const t of tags) if (!vocab.descriptors.has(t)) errors.push(`${where}: unknown descriptor "${t}"`);
      if (size !== undefined && !vocab.sizes.has(size)) errors.push(`${where}: unknown size "${size}"`);
    }
    const id = `${sheetBase(sheet)}_${col}_${row}`;
    if (seenIds.has(id)) {
      errors.push(`${where}: duplicate id "${id}" — pick a distinct tile (ids must be unique)`);
      continue;
    }
    seenIds.add(id);

    const cropped = cropTile(png, col, row);
    if (isBlank(cropped)) warns.push(`${where}: tile is fully transparent (blank slot?)`);

    manifest.push({
      id,
      category,
      sheet,
      col,
      row,
      ...(archetype ? { archetype } : {}),
      ...(kind ? { kind } : {}),
      ...(size ? { size } : {}),
      tags,
      name,
    });

    if (category === 'character') {
      archetypeTileCount[archetype] = (archetypeTileCount[archetype] ?? 0) + 1;
      // Resolver-facing tags: archetype FIRST (high weight), then descriptors, then size.
      const entryTags = [archetype, ...tags, ...(size ? [size] : [])];
      characterSprites.push({ id, tags: entryTags, src: pngToDataURI(cropped) });
    }
  }
}

if (errors.length) {
  console.error('[build:dawnlike] FAILED:\n  ' + errors.join('\n  '));
  process.exit(1);
}

// Coverage / variety warnings (don't fail — you author incrementally).
for (const a of vocab.archetypes) {
  const n = archetypeTileCount[a] ?? 0;
  if (n === 0) warns.push(`archetype "${a}" has no tiles (mobs of this type resolve to null until picked)`);
  else if (n < 2) warns.push(`archetype "${a}" has only 1 tile (no per-instance variety)`);
}

// categoryGenerics: first picked tile per archetype → guaranteed fallback.
const categoryGenerics = {};
for (const s of characterSprites) {
  const a = s.tags[0];
  if (!(a in categoryGenerics)) categoryGenerics[a] = s.id;
}

const OUT_DIR = path.join(REPO, 'src', 'packs');
fs.mkdirSync(OUT_DIR, { recursive: true });

fs.writeFileSync(
  path.join(OUT_DIR, 'dawnlike.manifest.json'),
  JSON.stringify(manifest, null, 2) + '\n',
);

const header = `/**
 * dawnlike.ts — GENERATED by tools/dawnlike/build-pack.mjs. Do not hand-edit.
 * Edit tools/dawnlike/picks.mjs and re-run \`npm run build:dawnlike\`.
 *
 * Art: DawnLike (DawnBringer's 16x16 universal rogue-like tileset) by DragonDePlatino,
 * licensed CC-BY-SA 3.0. The art in this file inherits CC-BY-SA 3.0; see CREDITS.md.
 */
import type { SpritePack } from '../pack.js';
`;

const body =
  `export const dawnlikeCharacterPack: SpritePack = {\n` +
  `  id: 'dawnlike-characters',\n` +
  `  name: 'DawnLike Characters',\n` +
  `  sprites: [\n` +
  characterSprites.map(s => `    ${JSON.stringify(s)},`).join('\n') +
  `\n  ],\n` +
  `  categoryGenerics: ${JSON.stringify(categoryGenerics, null, 2).replace(/\n/g, '\n  ')},\n` +
  `};\n`;

fs.writeFileSync(path.join(OUT_DIR, 'dawnlike.ts'), header + '\n' + body);

if (warns.length) console.warn('[build:dawnlike] notes:\n  ' + warns.join('\n  '));
console.log(
  `[build:dawnlike] ${characterSprites.length} character sprites, ${manifest.length} manifest entries → src/packs/dawnlike.{ts,manifest.json}`,
);
